workspace: true

stages:
  - install
  - test

jobs:
  - name: Install dependencies
    stage: install
    image: node:14-alpine
    only:
      branches:
        - master
    cache:
      - key: node_modules_$CI_BRANCH
        paths:
          - node_modules
    script:
      - yarn install
  - name: Check code
    stage: test
    image: node:14-alpine
    only:
      branches:
        - master
    script:
      - yarn run lint
      - yarn run test
