workspace: true

stages:
  - install
  - test

jobs:
  - name: Install dependencies
    stage: install
    image: node:16-alpine
    only:
      branches:
        - master
    script:
      - yarn install
  - name: Check code
    stage: test
    image: node:16-alpine
    only:
      branches:
        - master
    script:
      - yarn run lint
      - yarn run test
